services:
  db:
    container_name: telemetry_db
    image: postgres:17.5
    environment:
      POSTGRES_USER: telemetry_user
      POSTGRES_PASSWORD: telemetry_pass
      POSTGRES_DB: telemetry_db
    ports:
      - "5432:5432"
    volumes:
      - telemetry_data:/var/lib/postgresql/data

volumes:
  telemetry_data:
