name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Download dependencies
        run: |
          go mod download

      - name: Build
        run: |
          go build -v ./...

      - name: Tidy
        run: |
          go mod tidy
          if ! git diff --exit-code go.mod go.sum; then
            echo "::error::go.mod or go.sum is not tidy. Please run 'go mod tidy'."
            exit 1
          fi

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
          echo "::error::Code is not gofmt-ed. Please run 'gofmt -w .'"
          gofmt -d .
          exit 1
          fi

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
